name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Creating project folder if it doesn't exist"
            mkdir -p /home/ubuntu/examination
            cd /home/ubuntu/examination

            if [ ! -d "Hmm-Just-Code" ]; then
              echo "Cloning repository"
              git clone https://github.com/Ozodbek-cloud/Hmm-Just-Code-.git Hmm-Just-Code
            else
              echo "Repository already exists, pulling latest changes"
              cd Hmm-Just-Code
              git pull origin main
            fi

            cd /home/ubuntu/examination/Hmm-Just-Code

            echo "Stopping containers"
            sudo docker compose down

            echo "Building containers"
            sudo docker compose build

            echo "Running containers"
            sudo docker compose up -d
